server:
  port: 8080
  servlet:
    context-path: /hwkj/
  tomcat:
    uri-encoding: UTF-8  #tomcat 编码格式
  #spring:
 # datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
   # url: jdbc:mysql://127.0.0.1:3306/hwkj?useSSL=false
    #username: root
    #data-password: 123456
jdbc.driver: com.mysql.cj.jdbc.Driver
jdbc.url: jdbc:mysql://localhost:3306/hwkj?useSSL=false
jdbc.username: root
jdbc.password: 123456
mybatis_config_file_path: mybatis-config.xml
mapper_path: /mapper/**/**.xml
entity_package: hwkj.hwkj.entity

logging:
  level:
    hwkj.hwkj.dao: debug

spring:
  thymeleaf:
    cache: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  server:
    MaxFileSize: 100MB
    MaxRequestSize: 1024MB
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000    #连接超时时间（毫秒）
  mail:
    host: smtp.qq.com
    username: 931466973@qq.com
    password: rtwoifuphggtbffi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8  #请求编码格式
      enabled: true
      force: true
  #jackson:
    #time-zone: Asia/Shanghai
